
package com.sape.net.json.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-02T15:31:38.954+05:30
 * Generated source version: 2.7.18
 * 
 */
public final class ISubtraction_SubtractionImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.com/", "SubtractionImplService");

    private ISubtraction_SubtractionImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SubtractionImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SubtractionImplService ss = new SubtractionImplService(wsdlURL, SERVICE_NAME);
        ISubtraction port = ss.getSubtractionImplPort();  
        
        {
        System.out.println("Invoking subtract...");
        int _subtract_arg0 = -487462156;
        int _subtract_arg1 = 595302434;
        int _subtract__return = port.subtract(_subtract_arg0, _subtract_arg1);
        System.out.println("subtract.result=" + _subtract__return);


        }

        System.exit(0);
    }

}
